config/routes.rb
require 'sidekiq/web'

CsvImporter::Application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'
  
  root "pages#home"
  
  
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"
  
  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"
  
  devise_for :users
  
  namespace :api, path: '/', constraints: { subdomain: 'api' } do
    resources :leads
  end
  
  # constraints subdomain: 'api' do
  #   namespace :api, path: '/' do
  #     resources :leads, only: [:index, :show]
  #   end
  # end

  namespace :admin do
    root "base#index"
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    resources :posts
    resources :leads do
      collection { post :import }
    end
    resources :csv_imports do
      collection { post :import }
      member { get :mapping }
    end
  end
  
  resources :leads do
    collection { post :import }
  end

end

app/models/lead.rb
class Lead < ActiveRecord::Base
  # Requirements
  require 'smarter_csv'
  
  # Relations
  belongs_to :user
    
  # Validations
  validates_uniqueness_of :email, :scope => :user_id, :allow_blank => true, :on => :create
  validate :contactable
  
  # Callbacks
  after_validation :has_changed?, :on => :update
    
  # Pagination
  paginates_per 100
    
  # Scopes
  scope :birthdays, lambda {
    where("MONTH(birthday) = ?", Time.now.month )
    .order("updated_at DESC")
  }
  
  # Class Methods
  class << self
    
    def to_csv(options = {})
     CSV.generate do |csv|
       csv << column_names
       all.each do |lead|
         csv << lead.attributes.values_at(*column_names)
       end
     end
    end
      
    def search_and_order(search, page_number, format = nil)
      if format.nil? && search
        where("email LIKE ?", "%#{search.downcase}%").order(
        last_name: :desc, email: :asc
        ).page page_number
      elsif !format.nil? && search
        where("email LIKE ?", "%#{search.downcase}%").order(
        last_name: :desc, email: :asc
        )
      elsif !format.nil?
        order(last_name: :desc, email: :asc)
      else
        order(last_name: :desc, email: :asc).page page_number
      end
    end
    
    # Options For Select Fields
    def field_options
      [
        ['Do Not Import Field', :none],
        ['Full Name', :full_name],
        ['First Name', :first_name],
        ['Last Name', :last_name],
        ['Email', :email],
        ['Type', :type],
        ['Company', :company],
        ['Street Address', :address1],
        ['City/State/Zipcode', :address2],
        ['City', :city],
        ['State', :state],
        ['ZipCode', :zip],
        ['Source', :source],
        ['Group', :category],
        ['Mobile Phone', :phone_mobile],
        ['Business Phone', :phone_business],
        ['Home Phone', :phone_home],
        ['Fax Number', :fax_number],
        ['Temperature', :temperature],
        ['Birthday', :birthday],
        ['Anniversary', :anniversary],
        ['Spouse', :spouse],
        ['Home Purchase Date', :home_anniversary],
        ['Home Budget Price', :budget],
        ['Notes/Comments', :description]
      ]
    end
    
    def kind_options
      [
        ['Buyer', 'buyer'],
        ['Seller', 'seller'],
        ['Investor', 'investor'],
        ['Prospect', 'prospect'],
        ['Converted', 'converted'],
        ['Client', 'client'],
        ['Past Client', 'past_client'],
        ['Renter', 'renter'],
        ['Vendor', 'vendor'],
        ['Lender', 'lender'],
        ['Broker', 'broker'],
        ['Agent', 'agent'],
        ['Appraiser', 'appraiser'],
        ['Builder/Contractor', 'builder_contractor'],
        ['Sphere of Influence', 'sphere_of_influence'],
        ['Family/Relative', 'family_relative'],
        ['First Time Buyer', 'first_time_buyer'],
        ['Friend', 'friend'],
        ['Landlord', 'landlord'],
        ['Tenant', 'tenant'],
        ['Company', 'company'],
        
      ]
    end
    
    def source_options
      [
        ['Advertisement', 'advertisement'],
        ['Broker', 'broker'],
        ['Cold Call', 'cold_call'],
        ['Expired Listing', 'expired_listing'],
        ['Foreclosure', 'foreclosure'],
        ['Open House', 'open_house'],
        ['Past Customer', 'past_customer'],
        ['Personal Marketing', 'personal_marketing'],
        ['Referral', 'referral'],
        ['Sign Call', 'sign_call'],
        ['Walk-in', 'walk_in'],
        ['Webpage', 'webpage'],
        ['Conference', 'conference'],
        ['Other', 'other']
      ]
    end
  end
  
  # Instance Methods
  def has_changed?
    self.flagged = self.changed?
  end
  
  def name
    "#{first_name} #{last_name}"
  end
  
  def name_or_email
    if self.first_name
      "#{self.first_name} #{self.last_name}"
    else
      self.email || self.alt_email
    end
  end
  
  def position
    if company && title
      "#{title} at #{company}"
    elsif company && !title
      "#{company}"
    elsif !company && title
      "#{title}"
    else
      ''
    end
  end
  
  def street_address
    if address1 && address2
      "#{address1}<br/>#{address2}".html_safe
    elsif address1 && !address2
      "#{address1}"
    else
      nil
    end
  end
  
  def city_state_zip
    if city && state && zipcode
      "#{city}, #{state}<br/>#{zipcode}".html_safe
    else
      nil
    end
  end
    
  private
  
  # Custom Validation
  def contactable
    if email.blank? && phone_mobile.blank? && phone_home.blank? && phone_work.blank? && address1.blank?
      errors.add(:lead, "missing contact information. Add one or all of the following: Email, Phone Number, Address")
    end
  end
end

app/controllers/admin/leads_controller.rb
class Admin::LeadsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_lead, only: [:show, :edit, :update, :destroy]

  # GET /leads
  # GET /leads.json
  # GET /leads.xls
  # GET /leads.csv
  def index
    @leads = Lead.search_and_order(params[:search], params[:page], params[:format])
    respond_to do |format|
      format.html
      format.json { render json: @leads.to_json }
      format.csv  { render text: @leads.to_csv }
      format.xml  { render  xml: @leads }
      format.xls  { render  xls: @leads }
    end
  end

  # GET /leads/1
  # GET /leads/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: @lead.to_json }
      format.xml  { render  xml: @lead }
    end
  end

  # GET /leads/new
  def new
    @lead = Lead.new
  end

  # GET /leads/1/edit
  def edit
  end

  # POST /leads
  # POST /leads.json
  def create
    @lead = Lead.new(lead_params)

    respond_to do |format|
      if @lead.save
        format.html { redirect_to admin_lead_path(@lead), notice: 'Lead was successfully created.' }
        format.json { render :show, status: :created, location: @lead }
      else
        format.html { render :new }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leads/1
  # PATCH/PUT /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        format.html { redirect_to @lead, notice: 'Lead was successfully updated.' }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @lead.destroy
    respond_to do |format|
      format.html { redirect_to admin_leads_url, notice: 'Lead was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def import
    begin
      Lead.import(params[:file])
      redirect_to root_url, notice: "Leads imported"
    rescue
      redirect_to root_url, notice: "Invalid CSV file format."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @lead = Lead.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lead_params
      params.require(:lead).permit(:first_name, :last_name, :email, :kind, :address1, :address2, :city, :state, :zipcode, :source, :category, :company, :phone_mobile, :phone_home, :phone_fax, :phone_work, :birthday, :purchase_date, :budget, :purchase_price, :rating, :home_value, :entry_point, :alt_email, :status, :referred_by, :skype, :facebook, :gchat, :aol, :yahoo, :access, :user_id)
    end
end

app/controllers/api/leads_controller.rb
# 'API' Case Consistency
# config/initializers/inflections.rb
module API
  class LeadsController < ApplicationController
    #before_action :authenticate
    
    # GET /leads
    def index
      leads = Lead.all
      if user = params[:user]
        leads = leads.where(:user_id => user)
      end
      
      respond_to do |format|
        format.json { render json: leads, status: :ok }
        format.xml  { render  xml: leads, status: :ok }
      end
    end
    
    def show
      lead = Lead.find(params[:id])
      
      respond_to do |format|
        format.json { render json: lead, status: :ok } #status 200
        format.xml  { render  xml: lead, status: :ok }
      end
    end
    
    def create
      lead = Lead.new(lead_params)
      if lead.save
        head :no_content, location: lead #status 204
      else
        render json: lead.errors, status: :unprocessable_entity #status 422
      end
    end
    
    private
    
      def lead_params
        params.require(:lead).permit(:first_name, :last_name, :email, :kind, :address1, :address2, :city, :state, :zipcode, :source, :category, :company, :phone_mobile, :phone_home, :phone_fax, :phone_work, :birthday, :purchase_date, :budget, :purchase_price, :rating, :home_value, :entry_point, :alt_email, :status, :referred_by, :skype, :facebook, :gchat, :aol, :yahoo, :access, :user_id)
      end
      
      def authenticate
        authenticate_or_request_with_http_basic('Leads') do |email, password|
         User.authenticate(email, password) 
        end
      end
    
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_lead, only: [:show, :edit, :update, :destroy]

  # GET /leads
  # GET /leads.json
  def index
    @leads = Lead.search_and_order(params[:search], params[:page])
  end

  # GET /leads/1
  # GET /leads/1.json
  def show
  end

  # GET /leads/new
  def new
    @lead = Lead.new
  end

  # GET /leads/1/edit
  def edit
  end

  # POST /leads
  # POST /leads.json
  def create
    @lead = Lead.new(lead_params)

    respond_to do |format|
      if @lead.save
        format.html { redirect_to @lead, notice: 'Lead was successfully created.' }
        format.json { render :show, status: :created, location: @lead }
      else
        format.html { render :new }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leads/1
  # PATCH/PUT /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        format.html { redirect_to @lead, notice: 'Lead was successfully updated.' }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @lead.destroy
    respond_to do |format|
      format.html { redirect_to leads_url, notice: 'Lead was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def import
    begin
      Lead.import(params[:file])
      redirect_to root_url, notice: "Leads imported"
    rescue
      redirect_to root_url, notice: "Invalid CSV file format."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @lead = Lead.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lead_params
      params.require(:lead).permit(:first_name, :last_name, :email, :kind, :address1, :address2, :city, :state, :zipcode, :source, :category, :company, :phone_mobile, :phone_home, :phone_fax, :phone_work, :birthday, :purchase_date, :budget, :purchase_price, :rating, :home_value, :entry_point, :alt_email, :status, :referred_by, :skype, :facebook, :gchat, :aol, :yahoo, :access, :user_id)
    end
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/admin/leads/_form.html.erb
<%= form_for(@lead, url: admin_leads_path(@lead)) do |f| %>
  <% if @lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
      <% @lead.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :kind %><br>
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br>
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br>
    <%= f.text_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :phone_mobile %><br>
    <%= f.text_field :phone_mobile %>
  </div>
  <div class="field">
    <%= f.label :phone_home %><br>
    <%= f.text_field :phone_home %>
  </div>
  <div class="field">
    <%= f.label :phone_fax %><br>
    <%= f.text_field :phone_fax %>
  </div>
  <div class="field">
    <%= f.label :phone_work %><br>
    <%= f.text_field :phone_work %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday %>
  </div>
  <div class="field">
    <%= f.label :purchase_date %><br>
    <%= f.date_select :purchase_date %>
  </div>
  <div class="field">
    <%= f.label :budget %><br>
    <%= f.text_field :budget %>
  </div>
  <div class="field">
    <%= f.label :purchase_price %><br>
    <%= f.text_field :purchase_price %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :home_value %><br>
    <%= f.text_field :home_value %>
  </div>
  <div class="field">
    <%= f.label :entry_point %><br>
    <%= f.text_field :entry_point %>
  </div>
  <div class="field">
    <%= f.label :alt_email %><br>
    <%= f.text_field :alt_email %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :referred_by %><br>
    <%= f.text_field :referred_by %>
  </div>
  <div class="field">
    <%= f.label :skype %><br>
    <%= f.text_field :skype %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br>
    <%= f.text_field :facebook %>
  </div>
  <div class="field">
    <%= f.label :gchat %><br>
    <%= f.text_field :gchat %>
  </div>
  <div class="field">
    <%= f.label :aol %><br>
    <%= f.text_field :aol %>
  </div>
  <div class="field">
    <%= f.label :yahoo %><br>
    <%= f.text_field :yahoo %>
  </div>
  <div class="field">
    <%= f.label :access %><br>
    <%= f.text_field :access %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/leads/edit.html.erb
<h1>Editing Lead</h1>

<%= render 'form' %>

<%= link_to 'Show', @lead %> |
<%= link_to 'Back', leads_path %>

app/views/admin/leads/index.html.erb
<% title("Leads Database") %>
<div class='row' style='border-bottom: 3px solid #555555;'>
  <div class='col-md-7'>
    <h3>Leads Database</h3>
  </div>
  <div class='col-md-5 text-right' style='top:25px;'>
    <%= link_to 'Create Lead', new_admin_lead_path %> | <%= link_to 'Import Leads via CSV File', '#', onclick: "$('#file-uploader').toggle()" %> | Export: <%= link_to("CSV", admin_leads_path(format: "csv", search: params[:search])) %> | <%= link_to "Excel", admin_leads_path(format: 'xls', search: params[:search])%>
  </div>
</div>

<div class="text-center">
  <p><%= page_entries_info @leads %></p>
  <%= paginate @leads %>
</div>

<%= form_tag admin_leads_path, method: 'get', html: {role: "form"} do %>
<p>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil, class: "btn btn-sm btn-primary" %>
  <%= link_to "All", admin_leads_path, {class: "btn btn-sm btn-link"} %>
</p>
<% end %>

<table class='table table-bordered table-striped table-condensed' style='margin-top: 10px;font-size:11px'>
  <thead>
    <tr>
      <th>Entry Point</th>
      <th>name</th>
      <th>Email</th>
      <th>Kind</th>
      <th>Source</th>
      <th>Category</th>
      <th>Company</th>
      <th>Rating</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leads.each do |lead| %>
      <tr>
        <td><%= lead.entry_point %></td>
        <td><%= lead.first_name %> <%= lead.last_name %></td>
        <td><%= lead.email %></td>
        <td><%= lead.kind %></td>
        <td><%= lead.source %></td>
        <td><%= lead.category %></td>
        <td><%= lead.company %></td>
        <td><%= lead.rating %></td>
        <td><%= lead.status %></td>
        <td><%= link_to 'Show', admin_lead_path(lead) %></td>
        <td><%= link_to 'Edit', edit_admin_lead_path(lead) %></td>
        <td><%= link_to 'Destroy', admin_lead_path(lead.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/leads/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">First Name</Data></Cell>
        <Cell><Data ss:Type="String">Last Name</Data></Cell>
        <Cell><Data ss:Type="String">Email</Data></Cell>
        <Cell><Data ss:Type="String">Type</Data></Cell>
        <Cell><Data ss:Type="String">Address 1</Data></Cell>
        <Cell><Data ss:Type="String">Address 2</Data></Cell>
        <Cell><Data ss:Type="String">City</Data></Cell>
        <Cell><Data ss:Type="String">State</Data></Cell>
        <Cell><Data ss:Type="String">Postal Code</Data></Cell>
        <Cell><Data ss:Type="String">Source</Data></Cell>
        <Cell><Data ss:Type="String">Category</Data></Cell>
        <Cell><Data ss:Type="String">Company</Data></Cell>
        <Cell><Data ss:Type="String">Title</Data></Cell>
        <Cell><Data ss:Type="String">Mobile Phone</Data></Cell>
        <Cell><Data ss:Type="String">Home Phone</Data></Cell>
        <Cell><Data ss:Type="String">Fax Number</Data></Cell>
        <Cell><Data ss:Type="String">Work Phone</Data></Cell>
        <Cell><Data ss:Type="String">Birthday</Data></Cell>
        <Cell><Data ss:Type="String">Purchase Date</Data></Cell>
        <Cell><Data ss:Type="String">Budget</Data></Cell>
        <Cell><Data ss:Type="String">Purchase Price</Data></Cell>
        <Cell><Data ss:Type="String">Rating</Data></Cell>
        <Cell><Data ss:Type="String">Home Value</Data></Cell>
        <Cell><Data ss:Type="String">Website Entry Point</Data></Cell>
        <Cell><Data ss:Type="String">Alternate Email</Data></Cell>
        <Cell><Data ss:Type="String">Status</Data></Cell>
        <Cell><Data ss:Type="String">Referred By</Data></Cell>
        <Cell><Data ss:Type="String">Skype</Data></Cell>
        <Cell><Data ss:Type="String">Facebook</Data></Cell>
        <Cell><Data ss:Type="String">Google Chat</Data></Cell>
        <Cell><Data ss:Type="String">AOL</Data></Cell>
        <Cell><Data ss:Type="String">Yahoo</Data></Cell>
        <Cell><Data ss:Type="String">Comments</Data></Cell>
      </Row>
    <% @leads.each do |lead| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= lead.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.first_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.last_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.email %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.kind %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.address1 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.address2 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.city %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.state %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.zipcode %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.source %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.category %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.company %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.title %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.phone_mobile %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.phone_home %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.phone_fax %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.phone_work %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.birthday %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.purchase_date %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.budget %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.purchase_price %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.rating %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.home_value %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.entry_point %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.alt_email %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.status %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.referred_by %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.skype %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.facebook %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.gchat %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.aol %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.yahoo %></Data></Cell>
        <Cell><Data ss:Type="String"><%= lead.comments %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/admin/leads/new.html.erb
<h1>New Lead</h1>

<%= render 'form' %>

<%= link_to 'Back', leads_path %>

app/views/admin/leads/show.html.erb
<p id="notice"><%= notice %></p>

<div class='col-sm-3' style='font-size:10px;'>
  <div class='row well'>
  <p>
  <div style='font-size:14px;font-weight:bold;'><%= @lead.name %></div>
  <%= @lead.position %><br/>
  </p>
  <p>
    <span class='legend'><strong>Address</strong></span><br/>
    <%= @lead.address1 %> <%= @lead.address2 %><br/>
    <%= @lead.city %>, <%= @lead.state %><br/>
    <%= @lead.zipcode %>
  </p>
  <p>
    <strong>Email:</strong> <em><%= mail_to(@lead.email) %></em><br/>
    <strong>Other:</strong> <em><%= mail_to(@lead.alt_email) %></em>
  </p>
  <dl class='dl-horizontal'>
    <dt>M.Phone:</dt><dd><%= @lead.phone_mobile %></dd>
    <dt>H.Phone:</dt><dd><%= @lead.phone_home %></dd>
    <dt>W.Phone:</dt><dd><%= @lead.phone_work %></dd>
    <dt>Fax Num:</dt><dd><%= @lead.phone_fax %></dd>
  </dl>
  <% if @lead.comments %>
  
  <p>
    <span class='legend'><strong>Notes:</strong></span><br/>
    <%= @lead.comments %>
  </p>
  <% end %>
  
  </div>
  <div class='row well'>
  <legend style='font-size:14px;color:navy;'>Lead Summary</legend>
  <table class='table table-condensed table-striped'>
    <tr><th>Type:</th><td><%= @lead.kind %></td></tr>
    <tr><th>Category:</th><td><%= @lead.category %></td></tr>
    <tr><th>Status:</th><td><%= @lead.status %></td></tr>
    <tr><th>Source:</th><td><%= @lead.source %></td></tr>
    <tr><th>Entry Point:</th><td><%= @lead.entry_point %></td></tr>
    <tr><th>Rating:</th><td><%= @lead.rating %></td></tr>
    <tr><th>Referred by:</th><td></td></tr>
    <tr><th>Assigned To:</th><td></td></tr>
  </table>
  <p>
    <%= link_to 'Edit', edit_admin_lead_path(@lead) %> |
    <%= link_to 'Back', admin_leads_path %>
  </p>
  </div>
  
  <div class='row well'>
    <p>
      <strong>Birthday: </strong><%= @lead.birthday %><br/>
    </p>
    <p>
      <strong>Home Anniversary:</strong> <%= @lead.purchase_date %><br/>
    </p>
    <p>
      <strong>Budget:</strong> <%= number_to_currency(@lead.budget) %><br/>
    </p>
    <p>
      <strong>Purchase price: </strong><%= number_to_currency(@lead.purchase_price) %><br/>
    </p>
    <p>
      <strong>Home value:</strong> <%= number_to_currency(@lead.home_value) %><br/>
    </p>
  </div>
  
  <div class='row well'>
    <p>
      <strong>Skype:</strong>
      <%= @lead.skype %>
    </p>

    <p>
      <strong>Facebook:</strong>
      <%= @lead.facebook %>
    </p>

    <p>
      <strong>Gchat:</strong>
      <%= @lead.gchat %>
    </p>

    <p>
      <strong>Aol:</strong>
      <%= @lead.aol %>
    </p>

    <p>
      <strong>Yahoo:</strong>
      <%= @lead.yahoo %>
    </p>

    <p>
      <strong>Access:</strong>
      <%= @lead.access %>
    </p>

    <p>
      <strong>User:</strong>
      <%= @lead.user_id %>
    </p>
  </div>
</div>